config/routes.rb
# -*- encoding : utf-8 -*-
RoutingFilter::Locale.include_default_locale = true
Otwartezabytki::Application.routes.draw do
  filter :locale,    :exclude => /^\/(admin|users\/auth)/
  mount Tolk::Engine => '/admin/tolk', :as => 'tolk'

  # Active Admin can cause migrations to fail...
  ActiveAdmin.routes(self) rescue nil

  devise_for :users, :path_names => {
    :sign_in => 'login', :sign_out => 'logout',
  }, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :tags, :only => :index

  resources :users, :only => [:show, :edit, :update] do
    get :checked_relics
    get :my_routes
    get :walking_guides
    put :accept_of_terms_update
    delete :remove_avatar
  end

  resources :relics, :except => [:new, :create, :destroy] do
    member do
      match 'section/:section/edit', :to => 'relics#edit', :as => 'edit_section'
      match 'section/:section', :to => 'relics#show', :as => 'section', :via => :get
      match 'section/:section', :to => 'relics#update', :as => 'section', :via => :put
      get :download_zip
      post :adopt
      post :unadopt
      get :print
    end

    resources :photos, :documents, :entries, :links, :events
    resources :alerts, :only => [:new, :create]
  end

  get '/relics/:id', as: :original_relic, to: 'relics#show'

  resource :relicbuilder, :only => [:new, :update, :create] do
    get :administrative_level
    get :address
    get :geodistance
    get :details
    match 'photos', :via => [:get, :delete]
  end

  match '/widgets', :to => "widgets#index"

  namespace :widgets do
    with_options :only => [:show, :edit, :create, :update] do |w|
      w.resources :map_searches, :path => "/map_search"
      w.resources :add_relics, :path => "/add_relics"
    end

    resources :walking_guides, :path => "/walking_guide", except: [:index] do
      member do
        get :print
        get :preview
      end
    end

    resources :directions, :path => "/direction", except: [:index] do
      member do
        get :print
        get :configure
        get :preview
        get :waypoints
      end
    end

    resource :add_alert, only: :show, path: "/add_alert"
  end

  resources :translations, :only => [:edit, :update], :constraints => {:id => /[\w.]+/ }

  namespace :api do
    namespace :v1 do

      resource :info do
        get :relics
        get :places
        get :relic_photos
      end

      resources :relics do
        resources :photos
        collection do
          get :clusters
          get :suggestions
        end
      end

      # resources :voivodeships, :only => [:index, :show]
      # resources :districts, :only => [:index, :show]
      # resources :communes, :only => [:index, :show]
      resources :places, :only => [:index, :show, :results]
      resources :users, :only => [] do
        collection do
          get :api_key_request
        end
      end
    end
  end

  get 'suggester/query'
  get 'suggester/place'
  get 'suggester/place_from_poland', :as => :place_from_poland

  resources :tags, :only => [:create]
  resources :administrative_divisions, :only => [:index]

  get 'geocoder/search'

  match "/hello"                      => 'pages#hello', :id => 'hello', :as => :hello
  match "accept_terms"               => 'static_pages#accept_terms_of_service'

  I18n.available_locales.each do |locale|
    match "#{I18n.t('routes.pages', :locale => locale)}/:id" => 'pages#show', :as => :"#{locale.to_s.underscore}_page"
  end

  root :to => 'pages#show', :id => 'home'
end

app/models/relic/bounding_box.rb
# -*- encoding : utf-8 -*-
# require bounding_box_size method on class
module Relic::BoundingBox

  extend ActiveSupport::Concern

  def bounding_box
    equidistance_bounding_box(latitude, longitude, self.class.visible_from)
  end

  module ClassMethods
    def visible_from
      raise "Please overwrite visible_from method with bounding box width."
    end
  end

  private

  def equidistance_bounding_box(latitude, longitude, side)

    latitude_radians = (latitude / 180.0) * Math::PI
    longitude_radians = (longitude / 180.0) * Math::PI

    half_side = side / 2.0

    radius = 6371.01 # of the Earth
    pradius = radius * Math.cos(latitude_radians)

    lat_min = latitude_radians - half_side / radius
    lat_max = latitude_radians + half_side / radius
    lon_min = longitude_radians - half_side / pradius
    lon_max = longitude_radians + half_side / pradius

    rad2deg = lambda { |radians| radians / Math::PI * 180.0  }

    return [
      { lat: rad2deg[lat_max], lng: rad2deg[lon_min] },
      { lat: rad2deg[lat_min], lng: rad2deg[lon_max] }
    ]
  end
end

app/models/relic/place_caching.rb
# -*- encoding : utf-8 -*-
# this module caches location fields for quick access
module Relic::PlaceCaching
  extend ActiveSupport::Concern

  included do
    belongs_to :commune
    belongs_to :district
    belongs_to :voivodeship

    before_save :cache_location_fields, :if => :place_id_changed?

    attr_protected :commune, :district, :voivodeship, :commune_id, :district_id, :voivodeship_id
  end

  def place=(value)
    super
    cache_location_fields
  end

  def place_id=(value)
    self[:place_id] = value
    cache_location_fields
  end

  def cache_location_fields
    if self.place and self.polish_relic
      self.place.conditional_geocode!
      self.latitude       ||= self.place.latitude
      self.longitude      ||= self.place.longitude
      self.commune_id     = self.place.commune_id
      self.district_id    = self.place.commune.district_id
      self.voivodeship_id = self.place.commune.district.voivodeship_id
    end
  end

  def commune_id
    cache_location_fields unless self[:commune_id]
    self[:commune_id]
  end

  def district_id
    cache_location_fields unless self[:district_id]
    self[:district_id]
  end

  def voivodeship_id
    cache_location_fields unless self[:voivodeship_id]
    self[:voivodeship_id]
  end

  def commune
    Commune.cached(:find, :with => commune_id) if commune_id
  end

  def district
    District.cached(:find, :with => district_id) if district_id
  end

  def voivodeship
    Voivodeship.cached(:find, :with => voivodeship_id) if voivodeship_id
  end

  def place
    Place.cached(:find, :with => place_id) if place_id
  end
end

app/models/relic/validations.rb
# -*- encoding : utf-8 -*-
# this module caches location fields for quick access
module Relic::Validations
  extend ActiveSupport::Concern

  included do
    validates :place, :presence => true, :unless => :foreign_relic?

    # build step validations
    with_options :if => lambda{ |o| o.details_step? or o.photos_step? } do |step|
      step.validates :reason, :identification, :presence => true
    end

    with_options :if => :photos_step? do |step|
      step.validates :description, :presence => true
    end

    validates :identification, :presence => true, :if => :identification_changed?
    # nonsense
    # validate :date_must_be_parsed, :if => :dating_of_obj_changed?

    # api create validation
    validates :place, :identification, :description, :reason, :presence => true, :if => :created_via_api
  end
  # nonsense implementation
  # def date_must_be_parsed
  #   if date_start.blank? || date_end.blank?
  #     errors.add(:dating_of_obj, I18n.t("errors.messages.date_must_be_parsed"))
  #   end
  # end

  def invalid_step
    return 'details' if [:reason, :identification].any?{|k| errors.keys.include?(k)}
    return 'photos'  if [:description].any?{|k| errors.keys.include?(k)}
    'address'
  end

  def invalid_step_view
    self.build_state = "#{invalid_step}_step"
    invalid_step
  end


end

app/controllers/api/v1/relics_controller.rb
# -*- encoding : utf-8 -*-
module Api
  module V1
    class RelicsController < ApiController

      before_filter :api_authenticate
      before_filter :api_authorize, :only => [:create, :update]

      def suggestions
        collection
      end

      def index
        collection
      end

      def clusters
        collection
      end

      def show
        @relic = Relic.find(params[:id])
      end

      def create
        # TODO (missing model fields)
        params[:relic].delete(:state)
        # ----



        @relic = Relic.new(params[:relic])
        @relic.user_id = api_user.id
        @relic.created_via_api = true
        @relic.parent_id = params[:relic][:parent_id]
        @relic.reason = params[:relic][:reason]


        if @relic.save
          render :show
        else
          render :json => {:errors => @relic.errors}, :status => :unprocessable_entity
        end
      end

      def update
        @relic = Relic.find(params[:id])
        @relic.user_id = api_user.id

        if @relic.update_attributes(params[:relic])
          render :show
        else
          render :json => {:errors => @relic.errors}, :status => :unprocessable_entity
        end
      end

      private

      def collection
        p = params.slice(:query, :place, :from, :to, :categories, :state, :existence, :location, :has_photos, :has_description, :order, :latitude, :longitude, :bounding_box, :path, :radius, :per_page, :widget, :polygon, :distance)

        [:state, :existence].each do |key|
          if p[key] && !p[key].is_a?(Array)
            p[key] = p.delete(key).split(",")
          end
        end

        p[:lat] = p.delete(:latitude) if p[:latitude]
        p[:lon] = p.delete(:longitude) if p[:longitude]

        params[:search] = p.merge(:q => p.delete(:query))

        tsearch.load = true
        @relics = tsearch.perform
      end

    end
  end
end

app/helpers/relics_helper.rb
# -*- encoding : utf-8 -*-
module RelicsHelper
  def categories_facets_hash_for(relics = relics)
    relics.terms('categories', true).inject({}) { |m, t| m[t['term']] = t['count']; m }
  end

  def link_parent(relic)
    if relic.class == OriginalRelic
      param = original_relic_slug(relic)
      link_to(relic.identification, original_relic_path(param, original: true), remote: true)
    else
      link_to(relic.identification, [relic], remote: true)
    end
  end

  def link_subrelics(relic, current_relic)
    if relic.class == OriginalRelic
      path = original_relic_path(original_relic_slug(relic), original: true)
    else
      path = [relic]
    end
    link_to path, :class => 'subrelic-link js-go-to-top', :remote => true do
      content_tag :dl, :class => ('subrelic ' + (relic == current_relic ? 'type-current ' : '')).strip do
        subrelic_image(relic) + subrelic_desc(relic)
      end
    end
  end

  def subrelic_image(relic)
    content_tag :dd, class: 'subrelic-image' do
      image_tag(relic.main_photo.file.url(:icon), :size => '24x24', :class => 'thumb type-tiny', :alt => '')
    end
  end

  def subrelic_desc(relic)
    content_tag :dt, class: 'subrelic-name' do
      relic.identification
    end
  end

  def original_relic_slug(relic)
    slug = [relic.place.name, relic.identification].join('-').gsub(/\d+/, '').parameterize
    param = [relic.id, slug] * '-'
  end

  def categories_facets_hash
    return @categories_facets_hash if defined? @categories_facets_hash
    @categories_facets_hash = categories_facets_hash_for(relics)
  end

  def descendants_select(relic, form)
    collection = relic.root.descendants.created.
        order('identification').
        map { |d| [d.identification, d.id] }.
        insert(0, [t('activerecord.attributes.relic.relic_group'), relic.id])

    form.input(:relic_id, {
        as: :select,
        label: t('common.apply_to'),
        include_blank: false,
        required: false,
        collection: collection
    })
  end

  def state_facets
    labels = t('activerecord.attributes.relic.states').with_indifferent_access
    relics.terms('state', true).map do |t|
      ["#{labels[t['term']]} <span class='box'>#{t['count']}</span>".html_safe, t['term']]
    end
  end

  def existence_facets
    labels = t('activerecord.attributes.relic.existences').with_indifferent_access
    relics.terms('existence', true).map do |t|
      ["<span class='label'>#{labels[t['term']]}</span> <span class='box'>#{t['count']}</span>".html_safe, t['term']]
    end
  end

  def has_photos_facets
    labels = t('activerecord.attributes.relic.photos_facets').with_indifferent_access
    relics.terms('has_photos', true).map do |t|
      ["#{labels[t['term']]} <span class='box'>#{t['count']}</span>".html_safe, t['term']]
    end
  end

  def has_description_facets
    labels = t('activerecord.attributes.relic.description_facets').with_indifferent_access
    relics.terms('has_description', true).map do |t|
      ["#{labels[t['term']]} <span class='box'>#{t['count']}</span>".html_safe, t['term']]
    end
  end

  def disabled search, name
    key = "#{search.object_id}_#{name}"
    return @disabled if @disabled && @disabled[key]
    @disabled ||= {}
    @disabled[key] ||= relics.terms(name).inject([]) { |r, t|
      r << t['term'] if t['count'].zero?
      r
    } - search.send(name)
  end

  def order_collection
    [
        [t('views.relics.index.order.score'), 'score.desc'],
        [t('views.relics.index.order.az'), 'alfabethic.asc'],
        [t('views.relics.index.order.za'), 'alfabethic.desc'],
    ]
  end

  def link_to_section_tab(name)
    link_to_unless_current "<span>#{t "relic_tabs." + name.to_s + ".name"}</span>".html_safe, edit_section_relic_path(relic.id, name), :class => "js-edit-relic-load-modal"
  end

  def leafs_of(tree)
    case tree
      when Hash
        tree.map do |k, v|
          if v.blank? || v.empty?
            [k]
          else
            leafs_of(v)
          end
        end.flatten
      when Array
        tree.map { |v| leafs_of(v) }.flatten
      else
        [tree]
    end
  end

  def state_tag(relic)
    labels = t('activerecord.attributes.relic.states').with_indifferent_access
    content_tag :div, :class => 'tag' do
      content_tag :span, labels[relic.state], :class => relic.state
    end
  end

  def state_hint_tag(state, social = false)
    [
        (content_tag :div, :class => "tag" do
          content_tag(:span, t("views.relics.index.states.#{state}.header"), :class => state)
        end),
        content_tag(:div, t("views.relics.index.states.#{state}.info#{'_social' if social}"), :class => "text")
    ].join.html_safe
  end

  def format_localization(relic, reverse = nil)
    a = []
    if relic.foreign_relic?
      a = [relic.country, relic.fprovince, relic.fplace, relic.street]
    elsif reverse
      a << "województwo #{relic.voivodeship.name}"
      a << "powiat #{relic.district.name}"
      a << "gmina #{relic.commune.name}"
      a << relic.place.name
    else
      a << relic.voivodeship.name
      a << "pow. #{relic.district.name}"
      a << "gm. #{relic.commune.name}"
      a << [relic.place.name, relic.street].compact.join(' ')
    end
    reverse ? a.reject(&:blank?).reverse.join(", ") : a.reject(&:blank?).join(' » ')
  end

  def relic_stats
    return @relic_stats if defined? @relic_stats
    @relic_stats = {
        :unchecked => Relic.created.where(:state => 'unchecked').count,
        :checked => Relic.created.where(:state => 'checked').count,
        :filled => Relic.created.where(:state => 'filled').count,
        :total => Relic.created.count
    }
  end

  def get_all_creators

    counted_tab = []

    counted_tab += relic.users.map{|x| x.id}

    counted_tab += make_list(relic.all_photos) if relic.all_photos.exists?

    counted_tab += make_list(relic.documents) if relic.documents.exists?

    counted_tab += make_list(relic.entries) if relic.entries.exists?

    counted_tab += make_list(relic.events) if relic.events.exists?

    counted_tab += make_list(relic.alerts) if relic.alerts.exists?

    counted_tab += make_list(relic.links) if relic.links.exists?

    User.where(id: counted_tab.uniq).map{|x| content_tag(:li, x.username, class: 'small-li')}.join('')
  end

  private


  def make_list(collection)
    ids = collection.map do |col|
        col.user_id
    end
    return ids
  end

  def get_all_photos_with_unsaved
    if relic.is_any_group?
      relic.all_photos_with_unsaved.order('position_in_group_of_relics asc nulls first')
    else
      relic.photos.all
    end
  end

  def number_of_photos(photo)
    Relic.find(photo.relic_id).photos.count
  end

  def number_of_photos_in_group_of_relics(obj)
    if obj.class == Photo
      relic = Relic.find(obj.relic_id)
    elsif obj.class == Relic
      relic = obj
    end

    photos_count = 0

    if relic.is_group?
      photos_count += Relic.where(ancestry: relic.id.to_s).map(&:photos).flatten.count
      photos_count += relic.photos.count
    else
      photos_count += Relic.where(ancestry: relic.ancestry.to_s).map(&:photos).flatten.count if relic.ancestry.present?
      photos_count += Relic.find(relic.ancestry).photos.count
    end
    photos_count
   end
end

app/views/relics/edit/_attachments.html.haml
.row.attachment_list
  - for photo in relic.photos
    = form_tag section_relic_path(relic, :section => :events), :remote => true, :method => :put do
      = hidden_field_tag 'photo_id', photo.id
      = submit_tag 'choose', :type => "image", :src => photo.file.url(:midi)
.row
  = link_to edit_relic_path(relic, :section => 'photos'), :class => 'btn', :remote => true do
    %strong= t('views.relics.edit.add_attachement')
  = t('views.relics.edit.or')
  = link_to t('views.relics.edit.cancel'), edit_relic_path(relic, :section => :events), :class => "js-close-edit-relic"

app/views/relics/edit/_categories.html.haml
.row
  %script{ type: 'application/json', id: 'auto_categories' }
    != relic.auto_categories.to_json
  %script{ type: 'text/html', id: 'auto_categories_markup' }
    <span class="auto_categories" title="#{t('views.relics.show.categories.assigned_automatically', editable: false)}">*</span>
  = semantic_form_for relic, :url => section_relic_path(relic.id, :section => :categories), :remote => true do |f|
    = f.input :tags, :input_html => { :value => relic.tags.join(','), :style => "width: 680px", :multiple => true },
              :hint => t('formtastic.hints.relic.tags'), alt: t('oz_input_alts.edit_relic.relic_tags')
    .select
      %label= t('views.relics.edit.categories.name')
      .input
        %span.block= t('formtastic.hints.relic.categories')
        .column.column-first
          = f.input :categories, :as => :check_boxes,
            :collection => Category.first_column.invert, :label => "",
            :input_html => { :multiple => true },
            :hint => false
        .column.column-second
          = f.input :categories, :as => :check_boxes,
            :collection => Category.second_column.invert, :label => "",
            :input_html => { :multiple => true },
            :hint => false
        .column.column-third
          = f.input :categories, :as => :check_boxes,
            :collection => Category.third_column.invert, :label => "",
            :input_html => { :multiple => true },
            :hint => false

    .actions
      %button.js-piwik-edited-tag= t('views.relics.edit.save')
      = t('views.relics.edit.or')
      = link_to t('views.relics.edit.cancel'), relic_path(relic.id), :class => "cancel js-close-edit-relic"

app/views/relics/edit/_description.html.haml
.row
  = semantic_form_for relic, :url => section_relic_path(relic.id, :section => :description), :remote => true do |f|
    = f.input :description, :label => false, :input_html => { :class => "description redactor", :style => 'height: 190px;' },
     alt: t('oz_input_alts.edit_relic.relic_desc')
    = f.input :wlk_guide_description, :label => t('oz_input_alts.edit_relic.walking_guide_desc'), :input_html => { :class => "description redactor", :style => 'height: 190px;' },
     alt: t('oz_input_alts.edit_relic.walking_guide_desc')
    .reminder
      =t('views.relics.edit.reminder')
    .actions
      %button.js-piwik-edited-description= t('views.relics.edit.save')
      = t('views.relics.edit.or')
      = link_to t('views.relics.edit.cancel'), relic_path(relic.id), :class => "cancel js-close-edit-relic"

app/views/relics/edit/_documents.html.haml
.row
  = semantic_form_for relic, :url => section_relic_path(relic.id, :section => :documents), :html => { :multipart => true }, :remote => true  do |f|
    - relic.documents.each do |document|
      - if document.user_id == current_user.id
        = f.semantic_fields_for :documents, document do |f2|
          .document[f2.object]
            .column-left
              .preview{ :class => document.mime_class }
              - if document.user_id == current_user.id
                = link_to t('views.relics.edit.documents.delete_file'), relic_document_path(relic.id, document.id),
                  :method => :delete,
                  :remote => true,
                  :confirm => t('views.relics.edit.documents.delete_confirm', :editable => false),
                  :class => "remove_document"
            .column-right
              = f2.input :name, :input_html => { :class => "name" }, alt: t('oz_input_alts.edit_relic.relic_doc_title')
              = f2.input :description, :input_html => { :class => "description" }, alt: t('oz_input_alts.edit_relic.relic_doc_desc')
      - elsif document.saved?
        .document
          .column-left
            = link_to document.file.url do
              .preview{ :class => document.mime_class }
          .column-right
            %label= t('activerecord.attributes.document.name')
            %p= document.name
            %label= t('activerecord.attributes.document.description')
            %p= document.description

    .document.hidden
      .column-left
        .preview.preview-placeholder

      .column-right
        %p
          %strong= t('views.relics.edit.documents.loading')
          = link_to t('views.relics.edit.documents.cancel'), '#', :class => "cancel_upload"
        %p
          .progressbar
            .value 0%
    .document-upload
      .file-input-wrapper
        %button.btn-file-input
          - if relic.documents.length.zero?
            = t('views.relics.edit.documents.upload_first')
          - else
            = t('views.relics.edit.documents.upload')
        = file_field_tag "document[file]", :class => 'document_upload', :"data-url" => "#{relic_documents_path(relic.id)}"

    = f.input :documents_info, alt: t('oz_input_alts.edit_relic.relic_doc_where')
    .actions
      %button.js-piwik-edited-official-documents= t('views.relics.edit.save')
      = t('views.relics.edit.or')
      = link_to t('views.relics.edit.cancel'), relic_path(relic.id), :class => "cancel js-close-edit-relic"

app/views/relics/edit/_entries.html.haml
.row
  = semantic_form_for relic, :url => section_relic_path(relic.id, :section => :entries), :remote => true  do |f|
    = f.semantic_fields_for :entries, relic.entries.find(&:new_record?) do |f2|
      = f2.input :title, alt: t('oz_input_alts.edit_relic.relic_legend_title')
      = f2.input :body, :input_html => { :class => "redactor" }, alt: t('oz_input_alts.edit_relic.relic_legend_desc')
    .reminder
      =t('views.relics.edit.reminder')
    .actions
      %button.js-piwik-edited-interesting-fact= t('views.relics.edit.add_and_save')
      = t('views.relics.edit.or')
      = link_to t('views.relics.edit.cancel'), relic_path(relic.id), :class => "cancel js-close-edit-relic"

.row.entries-showcase{ :"data-replace" => (!params[:entry_id].nil? ? ".entries-showcase" : "#nonexistent") }
  - relic.entries.select{ |e| !e.new_record? }.sort_by(&:id).each do |entry|
    - if params[:entry_id].to_i == entry.id
      = semantic_form_for [relic, entry], :remote => true  do |f|
        = f.input :title, :hint => false, alt: t('oz_input_alts.edit_relic.relic_legend_title')
        = f.input :body, :hint => false, :input_html => { :class => "redactor" }, alt: t('oz_input_alts.edit_relic.relic_legend_desc')
        .actions
          = f.submit t('views.relics.edit.save')
          = link_to t('views.relics.edit.delete'), relic_entry_path(relic.id, entry.id), :method => :delete, :remote => true
          = t('views.relics.edit.or')
          = link_to t('views.relics.edit.cancel'), edit_section_relic_path(relic.id, :section => :entries, :entry_id => 0), :class => "cancel js-close-edit-relic"
    - else
      = content_tag_for :article, entry do
        %h3= entry.title
        .body= sanitize entry.body
        = link_to t('views.relics.edit.update'), edit_section_relic_path(relic.id, :section => :entries, :entry_id => entry.id),
          :remote => true,
          :class => "update"

app/views/relics/edit/_general.html.haml
.row
  = semantic_form_for relic, :url => section_relic_path(relic.id, :section => :general), :remote => true do |f|
    = f.input :identification, :as => :string, alt: t('oz_input_alts.edit_relic.relic_name')
    = f.input :common_name, :as => :string, alt: t('oz_input_alts.edit_relic.relic_common_name')
    .actions
      %button= t('views.relics.edit.save')
      = t('views.relics.edit.or')
      = link_to t('views.relics.edit.cancel'), relic_path(relic.id), :class => "cancel js-close-edit-relic"

app/views/relics/edit/_photos.html.haml
= semantic_form_for relic, :url => section_relic_path(relic.id, :section => :photos), :html => { :multipart => true }, :remote => true  do |f|
  .photo-attributes.oz-xs-sm-text-center
    -#- relic.photos.all.each do |photo|
    - correct_order = relic.is_group? ? get_all_photos_with_unsaved.position_group_order : get_all_photos_with_unsaved
    - correct_order.each do |photo|
      - if photo.user_id == current_user.id
        = f.semantic_fields_for :photos, photo do |f2|
          .col-md-12.col-xs-12.col-sm-12.photo[f2.object]
            .col-lg-3.col-sm-12.col-xs-12.no-margins.oz-xs-sm-no-float.text-center
              .preview
                = image_tag photo.file.midi.url, :alt => photo.alternate_text
              - if photo.user_id == current_user.id
                = link_to t('views.relics.edit.photos.delete_photo'), relic_photo_path(photo.relic_id, photo.id),
                  :method => :delete,
                  :remote => true,
                  :confirm => t('views.relics.edit.photos.delete_confirm', :editable => false),
                  :class => "remove_photo"
            .col-lg-9.col-sm-12.col-xs-12.oz-xs-sm-no-float
              = f2.input :author, :input_html => { :class => "author" }, alt: t('oz_input_alts.edit_relic.relic_photo_author')
              = f2.input :date_taken, :input_html => { :class => "date_taken" }, alt: t('oz_input_alts.edit_relic.relic_photo_date')
              = f2.input :description, :input_html => { :class => "description redactor" }, alt: t('oz_input_alts.edit_relic.relic_photo_desc')
              = f2.input :alternate_text, :input_html => { :class => "alternate_text" }, alt: t('oz_input_alts.edit_relic.relic_photo_alt')
              - if photo.relic_id == relic.id && !relic.is_group?
                = f2.input :position, :as => :select, :collection => (1..number_of_photos(photo)).to_a, :include_blank => false, alt: t('activerecord.attributes.photo.position')
              - else
                = f2.input :position_in_group_of_relics, :as => :select, :collection => (1..number_of_photos_in_group_of_relics(photo)).to_a, :include_blank => false, alt: t('activerecord.attributes.photo.position')
              - if relic.is_group?
                .apply-to
                  = descendants_select(relic, f2)

      - elsif photo.saved?
        .photo.col-md-12.col-sm-12.col-xs-12
          .col-lg-3.col-sm-12.col-xs-12.no-margins.oz-xs-sm-no-float
            .preview
              = image_tag photo.file.midi.url, alt: photo.alternate_text
          .col-lg-9.col-sm-12.col-xs-12.oz-xs-sm-no-float
            %label= t('activerecord.attributes.photo.author')
            %p= photo.author
            %label= t('activerecord.attributes.photo.date_taken')
            %p= photo.date_taken
            %label= t('activerecord.attributes.photo.description')
            %p= photo.description
            %label= t('activerecord.attributes.photo.alternate_text')
            %p= photo.alternate_text

            = f.semantic_fields_for :photos, photo do |f2|
              - if photo.relic_id == relic.id && !relic.is_group?
                = f2.input :position, :as => :select, :collection => (1..number_of_photos(photo)).to_a, :include_blank => false, alt: t('activerecord.attributes.photo.position')
              - else
                = f2.input :position_in_group_of_relics, :as => :select, :collection => (1..number_of_photos_in_group_of_relics(photo)).to_a, :include_blank => false, alt: t('activerecord.attributes.photo.position')
              - if relic.is_group?
                .apply-to
                  = descendants_select(relic, f2)

    .photo.hidden.col-sm-12.col-xs-12
      .column-left
        .preview.preview-placeholder
      .column-right
        %p
          %strong= t('views.relics.edit.photos.loading')
          = link_to t('views.relics.edit.cancel'), '#', :class => "cancel_upload"
        %p
          .progressbar
            .value 0%
    .photo-upload
      .file-input-wrapper
        %button.btn-file-input
          - if relic.photos.length.zero?
            = t('views.relics.edit.photos.upload_first')
          - else
            = t('views.relics.edit.photos.upload')
        = file_field_tag "photo[file]", :class => 'photo_upload js-piwik-added-a-new-photo', :"data-url" => "#{relic_photos_path(relic.id)}"
    .col-md-12.no-margins.license-agreement
      = f.input :license_agreement, :input_html => { :checked => 'checked' }, :as => :boolean, :label => t('views.relics.edit.photos.statement_html')
  .actions.col-md-12.col-xs-12.col-sm-12.oz-xs-sm-text-center
    %button= t('views.relics.edit.save')
    = t('views.relics.edit.or')
    = link_to t('views.relics.edit.cancel'), relic_path(relic.id), :class => "cancel js-close-edit-relic"