config/routes.rb
# -*- encoding : utf-8 -*-
RoutingFilter::Locale.include_default_locale = true
Otwartezabytki::Application.routes.draw do
  filter :locale,    :exclude => /^\/(admin|users\/auth)/
  mount Tolk::Engine => '/admin/tolk', :as => 'tolk'

  # Active Admin can cause migrations to fail...
  ActiveAdmin.routes(self) rescue nil

  devise_for :users, :path_names => {
    :sign_in => 'login', :sign_out => 'logout',
  }, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :tags, :only => :index

  resources :users, :only => [:show, :edit, :update] do
    get :checked_relics
    get :my_routes
    get :walking_guides
    put :accept_of_terms_update
    delete :remove_avatar
  end

  resources :relics, :except => [:new, :create, :destroy] do
    member do
      match 'section/:section/edit', :to => 'relics#edit', :as => 'edit_section'
      match 'section/:section', :to => 'relics#show', :as => 'section', :via => :get
      match 'section/:section', :to => 'relics#update', :as => 'section', :via => :put
      get :download_zip
      post :adopt
      post :unadopt
      get :print
    end

    resources :photos, :documents, :entries, :links, :events
    resources :alerts, :only => [:new, :create]
  end

  get '/relics/:id', as: :original_relic, to: 'relics#show'

  resource :relicbuilder, :only => [:new, :update, :create] do
    get :administrative_level
    get :address
    get :geodistance
    get :details
    match 'photos', :via => [:get, :delete]
  end

  match '/widgets', :to => "widgets#index"

  namespace :widgets do
    with_options :only => [:show, :edit, :create, :update] do |w|
      w.resources :map_searches, :path => "/map_search"
      w.resources :add_relics, :path => "/add_relics"
    end

    resources :walking_guides, :path => "/walking_guide", except: [:index] do
      member do
        get :print
        get :preview
      end
    end

    resources :directions, :path => "/direction", except: [:index] do
      member do
        get :print
        get :configure
        get :preview
        get :waypoints
      end
    end

    resource :add_alert, only: :show, path: "/add_alert"
  end

  resources :translations, :only => [:edit, :update], :constraints => {:id => /[\w.]+/ }

  namespace :api do
    namespace :v1 do

      resource :info do
        get :relics
        get :places
        get :relic_photos
      end

      resources :relics do
        resources :photos
        collection do
          get :clusters
          get :suggestions
        end
      end

      # resources :voivodeships, :only => [:index, :show]
      # resources :districts, :only => [:index, :show]
      # resources :communes, :only => [:index, :show]
      resources :places, :only => [:index, :show, :results]
      resources :users, :only => [] do
        collection do
          get :api_key_request
        end
      end
    end
  end

  get 'suggester/query'
  get 'suggester/place'
  get 'suggester/place_from_poland', :as => :place_from_poland

  resources :tags, :only => [:create]
  resources :administrative_divisions, :only => [:index]

  get 'geocoder/search'

  match "/hello"                      => 'pages#hello', :id => 'hello', :as => :hello
  match "accept_terms"               => 'static_pages#accept_terms_of_service'

  I18n.available_locales.each do |locale|
    match "#{I18n.t('routes.pages', :locale => locale)}/:id" => 'pages#show', :as => :"#{locale.to_s.underscore}_page"
  end

  root :to => 'pages#show', :id => 'home'
end

app/models/widget.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: widgets
#
#  id                 :integer          not null, primary key
#  user_id            :integer
#  widget_template_id :integer
#  uid                :string(255)
#  config             :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Widget < ActiveRecord::Base
  attr_accessible :config, :as => [:default, :admin]

  serialize :config, Hash

  extend FriendlyId
  friendly_id :uid

  def snippet
    ""
  end

  class << self
    include ActionView::Helpers::TagHelper
    include ActionView::Helpers::AssetTagHelper

    def thumb
      "widgets/#{partial_name}.png"
    end

    def title
      I18n.t("widget.#{partial_name}.title")
    end

    def description
      I18n.t("widget.#{partial_name}.description")
    end

    def partial_name
      name.underscore.split('/').last
    end

    def serialized_attr_accessor(*args)
      args.flat_map{ |e| e.is_a?(Hash) ? e.to_a : [[e, nil]] }.each do |(method_name, default_value)|
        if default_value == true || default_value == false
          define_method(method_name) do
            !!((self.attributes['config'] || {})[method_name])
          end
        else
          define_method(method_name) do
            (self.attributes['config'] || {})[method_name] || default_value
          end
        end

        if default_value.is_a?(Integer)
          define_method("#{method_name}=") do |value|
            self.attributes['config'] ||= {}
            self.attributes['config'][method_name] = value.to_i
          end
        elsif default_value == true || default_value == false
          define_method("#{method_name}=") do |value|
            self.attributes['config'] ||= {}
            self.attributes['config'][method_name] = string_to_bool(value)
          end
        else
          define_method("#{method_name}=") do |value|
            self.attributes['config'] ||= {}
            self.attributes['config'][method_name] = value
          end
        end

        attr_accessible method_name, "#{method_name}=", :as => [:default, :admin]
      end
    end
  end

  protected

  before_create :generate_uid

  def generate_uid
    self.uid ||= Devise.friendly_token
  end

  def string_to_bool(value)
    return true if value == true || value =~ (/(true|t|yes|y|1)$/i)
    return false if value == false || value.blank? || value =~ (/(false|f|no|n|0)$/i)
    raise ArgumentError.new("invalid value for Boolean: \"#{value}\"")
  end
end

app/controllers/widgets/add_alerts_controller.rb
# -*- encoding : utf-8 -*-

class Widgets::AddAlertsController < WidgetsController

  expose(:widget_add_alerts, model: Widget::AddAlert)
  expose(:widget_add_alert,  model: Widget::AddAlert)

  expose(:widget) do
    if params[:id].present?
      widget_add_alerts.find(params[:id])
    else
      Widget::AddAlert.new(:relic_id => params[:relic_id])
    end
  end

  helper_method :searched_relics

  def show
    render(partial: "/widgets/show/add_alert", layout: false) if params[:raw]
  end

  def create
    if widget_add_alert.save
      redirect_to edit_widgets_add_alert_path(widget_add_alert)
    else
      redirect_to widgets_path :error => t('notices.widget_error')
    end
  end

  def update
    if widget.relic_id != widget_add_alert.relic_id and widget_add_alert.save
      redirect_to edit_widgets_add_alert_path(widget_add_alert), :notice => t('notices.widget_has_been_updated')
    else
      render :edit
    end
  end

  protected
    def searched_relics
      @searched_relics ||= Search.new(:q => widget_add_alert.q, :load => true).perform.results if widget_add_alert.q.present?
    end

end

app/controllers/widgets/add_relics_controller.rb
# -*- encoding : utf-8 -*-

class Widgets::AddRelicsController < WidgetsController

  expose(:widget_add_relics, model: Widget::AddRelic)
  expose(:widget_add_relic,  model: Widget::AddRelic)
  expose(:widget) { widget_add_relics.find(params[:id]) }

  def create
    if widget_add_relic.save
      redirect_to edit_widgets_add_relic_path(widget_add_relic)
    else
      edirect_to widgets_path :error => t('notices.widget_error')
    end
  end

  def update
    if widget_add_relic.save
      redirect_to edit_widgets_add_relic_path(widget_add_relic), :notice => t('notices.widget_has_been_updated')
    else
      flash[:error] = t('notices.widget_error_and_correct')
      render :edit
    end
  end

end

app/controllers/widgets/directions_controller.rb
# -*- encoding : utf-8 -*-

class Widgets::DirectionsController < WidgetsController
  layout :resolve_widget_layout, :only => [:show, :configure]

  expose(:widget_directions, model: Widget::Direction)
  expose(:widget_direction,  model: Widget::Direction)
  expose(:widget) { widget_directions.find(params[:id]) }
  expose(:widget_params) { widget.widget_params }
  expose(:categories) { widget.widget_params.try(:[], 'categories') || [] }

  expose(:widget_search) do
    params[:search] ||= { :location => 'country:pl' }
    Search.new(params[:search].merge(:widget => "1"))
  end

  expose(:relics) do
    widget_search.load = true
    widget_search.perform
  end

  prepend_before_filter -> { params[:skip_return_path] = true }, only: [:show, :configure, :print]
  before_filter :set_cache_buster, only: [:waypoints]

  def show
    widget_search
    relics
  end

  def create
    if widget_direction.save
      redirect_to edit_widgets_direction_path(widget_direction)
    else
      redirect_to widgets_path :error => t('notices.widget_error')
    end
  end

  def edit
    authorize! :edit, widget_direction if widget_direction.user_id
  end

  def update
    authorize! :update, widget_direction if widget_direction.user_id

    if params[:save] || params[:save_and_print]
      # Assign user_id only on manual save action
      widget_direction.user_id ||= current_user.try(:id)
    end

    respond_to do |format|
      if widget_direction.has_valid_waypoints?
        if widget_direction.save
          format.json { head :ok }
          format.html do
            if params[:save_and_print]
              redirect_to print_widgets_direction_path(widget_direction)
            else
              redirect_to edit_widgets_direction_path(widget_direction), :notice => (t('widget.direction.save') if current_user)
            end
          end
        else
          format.json { head :unprocessable_entity }
          format.html do
            flash[:notice] = t('notices.widget_error_and_correct') if current_user
            render :edit
          end
        end
      else
        format.json { head :unprocessable_entity }
        format.html do
          flash[:notice] = t('widget.direction.no_route') if current_user
          redirect_to edit_widgets_direction_path(widget_direction)
        end
      end
    end
  end

  def print
    render :print, :layout => 'widgets/print'
  end

  def preview
  end

  def configure
  end

  def destroy
    authorize! :destroy, widget_direction
    widget_direction.destroy
    redirect_to user_my_routes_path(current_user.id), :notice => t('notices.route_has_been_removed')
  end

  def waypoints
    render json: widget_direction.widget_params.try(:[], 'waypoints') || []
  end

  protected

  def with_return_path
    request.path
  end

  def set_cache_buster
    response.headers['Cache-Control'] = 'no-cache, no-store, max-age=0, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = 'Fri, 01 Jan 1990 00:00:00 GMT'
  end

end

app/controllers/widgets/map_searches_controller.rb
# -*- encoding : utf-8 -*-

class Widgets::MapSearchesController < WidgetsController

  expose(:widget_map_searches, model: Widget::MapSearch)
  expose(:widget_map_search,   model: Widget::MapSearch)
  expose(:widget) { widget_map_searches.find(params[:id]) }

  expose(:widget_search) do
    params[:search] ||= { :location => 'country:pl' }
    Search.new(params[:search].merge(:widget => "1", :per_page => 100))
  end

  expose(:relics) do
    widget_search.load = true
    widget_search.perform
  end

  def show
    widget_search
    relics
  end

  def create
    if widget_map_search.save
      redirect_to edit_widgets_map_search_path(widget_map_search.id)
    else
      redirect_to widgets_path :error => t('notices.widget_error')
    end
  end

  def update
    if widget_map_search.save
      redirect_to edit_widgets_map_search_path(widget_map_search.id), :notice => t('notices.widget_has_been_updated')
    else
      flash[:error] = t('notices.widget_error_and_correct')
      render :edit
    end
  end

end

app/controllers/widgets/timelines_controller.rb
# -*- encoding : utf-8 -*-

class Widgets::TimelinesController < WidgetsController

  expose(:widget_timelines) { Widget::Timeline.scoped }
  expose(:widget_timeline)
  expose(:widget) { widget_timelines.find(params[:id]) }

  expose(:widget_search) do
    params[:search] ||= { :location => 'country:pl' }
    Search.new(params[:search].merge(:widget => "1"))
  end

  expose(:relics) do
    widget_search.load = true
    widget_search.perform
  end

  def show
    widget_search
    relics
  end

  def create
    if widget_timeline.save
      redirect_to edit_widgets_timeline_path(widget_timeline.id)
    else
      redirect_to widgets_path :error => t('notices.widget_error')
    end
  end

  def update
    if widget_timeline.save
      redirect_to edit_widgets_timeline_path(widget_timeline.id), :notice => t('notices.widget_has_been_updated')
    else
      flash[:error] = t('notices.widget_error_and_correct')
      render :edit
    end
  end

end

app/controllers/widgets/walking_guides_controller.rb
class Widgets::WalkingGuidesController < WidgetsController
  layout :resolve_widget_layout, :only => [:show]

  expose(:walking_guides, model: Widget::WalkingGuide)
  expose(:walking_guide, model: Widget::WalkingGuide)
  expose(:widget_params) { widget.widget_params }
  expose(:widget) { walking_guides.find(params[:id]) }

  def new

  end

  def show

    if walking_guide.private.blank? or !walking_guide.private or (current_user.present? and  walking_guide.user_id == current_user.id)
      respond_to do |format|
        format.html
        format.json { render :walking_guide }
      end
    elsif current_user.present? and  walking_guide.user_id != current_user.id
        render403
    else
      redirect_to new_user_session_url
    end
  end

  def create
    set_user_id
    if walking_guide.save
      remember_path
      render :walking_guide
    else
      render json: {errors: walking_guide.errors}, status: :unprocessable_entity
    end
  end

  def edit
    authorize! :edit, walking_guide if walking_guide.user_id
  end

  def update
    authorize! :update, walking_guide if walking_guide.user_id

    set_user_id
    if walking_guide.save
      remember_path
      render :walking_guide
    else
      render json: {errors: walking_guide.errors}, status: :unprocessable_entity
    end
  end

  def print
    render :print, layout: 'widgets/print'
  end

  def preview

  end

  def destroy
    authorize! :destroy, walking_guide
    walking_guide.destroy
    respond_to do |format|
      format.html do
        redirect_to user_walking_guides_path(current_user.id), :notice => t('notices.walking_guide_has_been_removed')
      end
      format.json { head :ok }
    end
  end

  private

  def remember_path
    set_return_path(edit_widgets_walking_guide_path(walking_guide))
  end

  def set_user_id
    return unless params[:manual]
    walking_guide.user_id ||= current_user.try(:id)
  end

end

app/controllers/widgets_controller.rb
# -*- encoding : utf-8 -*-
class WidgetsController < ApplicationController
  layout :resolve_widget_layout, :only => :show

  def resolve_widget_layout
    request.xhr? ? 'ajax' : 'widget'
  end

end

app/helpers/widgets_helper.rb
# -*- encoding : utf-8 -*-
module WidgetsHelper

  # Converts facet from search results to Hash
  # containing data relevant to map search widget
  def facet_to_marker(place)
    {
      :type => place.class.name.underscore,
      :id => place.class == Commune ? place.virtual_id : place.id.to_s,
      :facet_count => place.facet_count,
      :latitude => place.latitude,
      :longitude => place.longitude,
      :bounding_box => place.bounding_box
    }
  end

  # Converts Relic object to Hash
  # containing data relevant to map search widget
  def relic_to_widget_data(relic, with_photo = true)
    data = {
      :id => relic.id,
      :latitude => relic.latitude,
      :longitude => relic.longitude,
      :identification => relic.identification,
      :street => relic.street,
      :place => relic.place.name
    }
    data[:main_photo] = relic.main_photo if with_photo
    data
  end

  def relic_to_widget_data_short(relic)
    [relic.id, relic.latitude, relic.longitude]
  end

  def route_type_collection
    ['walking', 'bicycling', 'driving'].map do |type|
      [I18n.t("views.widgets.route_types.#{type}"), type]
    end
  end

  def selected_categories(selected)
    categories = []
    Category.roots.sort_by(&:name).map do |category|
      if category.name_key == 'sakralny'
        category.children.sort_by(&:name).each do |child|
          categories << child.name.gsub('/', ', ') if selected.include?(child.name_key)
        end
      elsif selected.include?(category.name_key)
        categories << category.name.gsub('/', ', ')
      end
    end
    categories
  end
end

app/views/widgets/edit/_add_alert.html.haml
%h1
  = t("widget.#{widget.class.partial_name}.title")
  %a.back{:href => widgets_path}= t('views.widgets.edit.back')
.sidebar
  = semantic_form_for widget_add_alert, :url => self.send("widgets_#{widget.class.partial_name}_path", widget) do |f|
    = f.input :relic_id, :as => :hidden, :label => false
    = f.input :q, :label => false, :hint => t('views.widgets.edit.add_alert.hint')
    = f.button t('views.widgets.edit.add_alert.search'), :class => 'use-widget'
    .clearfix
    - if searched_relics.present?
      %h3=t('views.widgets.edit.add_alert.which_one')
      .relics-wrapper
        %ul.relics
          - searched_relics.each do |relic|
            %li
              = link_to t('views.relicbuilders.new.choose_html'), 'javascript: void(0);', 'data-relic_id' => relic.id, 'data-identification' => relic.identification
              %strong= relic.identification
.content
  - if widget.valid?
    %h2= t('views.widgets.edit.preview')
    .preview
      = raw(widget.snippet)
    %h2= t('views.widgets.edit.generated')
    %div
      %span.block= t('views.widgets.edit.code_help')
      %textarea{:cols => "20", :rows => "3"}= widget.snippet

- content_for(:footer_javascripts) do
  :coffeescript
    jQuery("a[data-relic_id]").click (e) ->
      $('#widget_add_alert_relic_id').val $(this).data('relic_id')
      $(this).parents('form').submit()

app/views/widgets/edit/_add_relic.html.haml
%h1
  = t("widget.#{widget.class.partial_name}.title")
  %a.back{:href => widgets_path}= t('views.widgets.edit.back')
.content
  - if widget.valid?
    %h2= t('views.widgets.edit.preview')
    .preview
      = raw(widget.snippet)
    %h2= t('views.widgets.edit.generated')
    %div
      %span.block= t('views.widgets.edit.code_help')
      %textarea{:cols => "20", :rows => "3"}= widget.snippet

app/views/widgets/edit/_direction.html.haml
%h1
  = t("widget.direction.title_")
  = link_to t('views.widgets.edit.direction.create_new_widget'), widgets_directions_path, :method => :post, :class => 'back hidden-xs'

  %a.back.hidden-xs{:href => widgets_path}= t('views.widgets.edit.back')
.content
  = link_to t('views.widgets.edit.direction.create_new_widget'), widgets_directions_path, :method => :post, :class => 'back visible-xs'
  %a.back.visible-xs{:href => widgets_path}= t('views.widgets.edit.back')
  %h2.oz-header= t('views.widgets.edit.direction.header')
  %span.block= t('views.widgets.edit.direction.settings_info_')
  - if current_user.blank?
    %span.block= t('views.widgets.edit.direction.sign_in_before_save')
  .preview
    %iframe#oz_direction{ width: "100%",  src: configure_widgets_direction_url(widget, iframe: true), scrolling: 'auto' }
  .sidebar.col-md-12.col-xs-12
    = semantic_form_for widget, :url => self.send("widgets_#{widget.class.partial_name}_path", widget) do |f|
      .col-lg-5.col-md-6.col-sm-12.oz-xy-widget.oz-no-margin
        .col-sm-6.col-xs-12.oz-no-margin= f.input :width, :label => t('views.widgets.edit.direction.width'), :required => false
        .col-sm-6.col-xs-12.oz-no-margin= f.input :height, :label => t('views.widgets.edit.direction.height'), :required => false
        = f.input :params, :as => :hidden, label: false
      .col-lg-7.col-md-6.col-sm-12.col-xs-12.oz-print-save.oz-no-margin
        - if current_user.present?
          .col-md-7.col-sm-6.col-xs-12.oz-no-margin
            = f.button t('views.widgets.edit.direction.save_and_print'), name: 'save_and_print', class: 'button oz-print-btn'
          .col-md-5.col-sm-6.col-xs-12.oz-no-margin
            = f.button t('views.widgets.edit.direction.save'), name: 'save', class: 'button oz-login-for-save'
        - else
          .col-md-5.col-sm-6.col-xs-12.oz-no-margin
            = link_to t('views.widgets.edit.direction.print_'), print_widgets_direction_path, :class => 'button oz-print-btn'
          .col-md-7.col-sm-6.col-xs-12.oz-no-margin
            .hidden-xs= link_to t('views.widgets.edit.direction.sign_in'), new_user_session_path(return_path: edit_widgets_direction_path(widget)), class: 'button oz-login-for-save'
            .visible-xs.oz-dir-login-flex= link_to t('views.widgets.edit.direction.sign_in_xs'), new_user_session_path(return_path: edit_widgets_direction_path(widget)), class: 'button oz-login-for-save'
  %h2.col-md-12.col-xs-12.oz-gen-text= t('views.widgets.edit.generated')
  %div.col-md-12.col-xs-12.oz-code-gen
    %span.block= t('views.widgets.edit.code_help')
    %textarea#snippet= widget.snippet

app/views/widgets/edit/_direction.html.slim
h1
  = t("widget.#{widget.class.partial_name}.title")
  a.back href=widgets_path
    = t('views.widgets.edit.back')

.widget-editor
  .grid
    .grid__cell.unit-1-4= render 'widgets/directions/form'
    .grid__cell.unit-3-4= render 'widgets/show/direction'

  .widget-settings
    = semantic_form_for widget, :url => self.send("widgets_#{widget.class.partial_name}_path", widget), :remote => true do |f|
      = f.input :width, :label => t('views.widgets.edit.direction.width'), :required => false
      = f.input :height, :label => t('views.widgets.edit.direction.height'), :required => false
      = f.input :params, :as => :hidden, label: false
      = f.button t('views.widgets.edit.direction.save'), name: 'manual_save'
      = link_to t('views.widgets.edit.direction.print'), print_widgets_direction_path
  h2= t('views.widgets.edit.generated')
  div
    span.block= t('views.widgets.edit.code_help')
    textarea#snippet cols="20" rows="3"
      = widget.snippet

app/views/widgets/edit/_map_search.html.haml
%h1
  = t("widget.#{widget.class.partial_name}.title")
  %a.back{:href => widgets_path}= t('views.widgets.edit.back')
- if widget.valid?
  .content
    %h2= t('views.widgets.edit.map_search.header')
    %span.block= t('views.widgets.edit.map_search.settings_info')
    .preview
      = raw(widget.snippet)
    .sidebar
      = semantic_form_for widget, :url => self.send("widgets_#{widget.class.partial_name}_path", widget), :remote => true do |f|
        = f.input :width, :label => t('views.widgets.edit.map_search.width'), :required => false
        = f.input :height, :label => t('views.widgets.edit.map_search.height'), :required => false
        = f.input :hide_sidebar, :as => :boolean, :label => t('views.widgets.edit.map_search.hide_sidebar'), :required => false
        = f.input :api_params, :as => :text, :label => t('views.widgets.edit.map_search.params_label'), :hint => t('views.widgets.edit.map_search.params_hint'), :input_html => { :readonly => "readonly" }
    %h2= t('views.widgets.edit.generated')
    %div
      %span.block= t('views.widgets.edit.code_help')
      %textarea#snippet{:cols => "20", :rows => "3"}= widget.snippet

app/views/widgets/edit/_timeline.html.haml
%h1
  = t("widget.#{widget.class.partial_name}.title")
  %a.back{:href => widgets_path}= t('views.widgets.edit.back')
- if widget.valid?
  .content
    %h2= t('views.widgets.edit.timeline.header')
    %span.block= t('views.widgets.edit.timeline.settings_info')
    .preview
      = raw(widget.snippet)
    .sidebar
      = semantic_form_for widget, :url => self.send("widgets_#{widget.class.partial_name}_path", widget), :remote => true do |f|
        = f.input :width, :label => t('views.widgets.edit.timeline.width'), :required => false
        = f.input :height, :label => t('views.widgets.edit.timeline.height'), :required => false
        = f.input :hide_sidebar, :as => :boolean, :label => t('views.widgets.edit.timeline.hide_sidebar'), :required => false
        = f.input :api_params, :as => :text, :label => t('views.widgets.edit.timeline.params_label'), :hint => t('views.widgets.edit.timeline.params_hint'), :input_html => { :readonly => "readonly" }
    %h2= t('views.widgets.edit.generated')
    %div
      %span.block= t('views.widgets.edit.code_help')
      %textarea#snippet{:cols => "20", :rows => "3"}= widget.snippet