config/routes.rb
# -*- encoding : utf-8 -*-
RoutingFilter::Locale.include_default_locale = true
Otwartezabytki::Application.routes.draw do
  filter :locale,    :exclude => /^\/(admin|users\/auth)/
  mount Tolk::Engine => '/admin/tolk', :as => 'tolk'

  # Active Admin can cause migrations to fail...
  ActiveAdmin.routes(self) rescue nil

  devise_for :users, :path_names => {
    :sign_in => 'login', :sign_out => 'logout',
  }, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :tags, :only => :index

  resources :users, :only => [:show, :edit, :update] do
    get :checked_relics
    get :my_routes
    get :walking_guides
    put :accept_of_terms_update
    delete :remove_avatar
  end

  resources :relics, :except => [:new, :create, :destroy] do
    member do
      match 'section/:section/edit', :to => 'relics#edit', :as => 'edit_section'
      match 'section/:section', :to => 'relics#show', :as => 'section', :via => :get
      match 'section/:section', :to => 'relics#update', :as => 'section', :via => :put
      get :download_zip
      post :adopt
      post :unadopt
      get :print
    end

    resources :photos, :documents, :entries, :links, :events
    resources :alerts, :only => [:new, :create]
  end

  get '/relics/:id', as: :original_relic, to: 'relics#show'

  resource :relicbuilder, :only => [:new, :update, :create] do
    get :administrative_level
    get :address
    get :geodistance
    get :details
    match 'photos', :via => [:get, :delete]
  end

  match '/widgets', :to => "widgets#index"

  namespace :widgets do
    with_options :only => [:show, :edit, :create, :update] do |w|
      w.resources :map_searches, :path => "/map_search"
      w.resources :add_relics, :path => "/add_relics"
    end

    resources :walking_guides, :path => "/walking_guide", except: [:index] do
      member do
        get :print
        get :preview
      end
    end

    resources :directions, :path => "/direction", except: [:index] do
      member do
        get :print
        get :configure
        get :preview
        get :waypoints
      end
    end

    resource :add_alert, only: :show, path: "/add_alert"
  end

  resources :translations, :only => [:edit, :update], :constraints => {:id => /[\w.]+/ }

  namespace :api do
    namespace :v1 do

      resource :info do
        get :relics
        get :places
        get :relic_photos
      end

      resources :relics do
        resources :photos
        collection do
          get :clusters
          get :suggestions
        end
      end

      # resources :voivodeships, :only => [:index, :show]
      # resources :districts, :only => [:index, :show]
      # resources :communes, :only => [:index, :show]
      resources :places, :only => [:index, :show, :results]
      resources :users, :only => [] do
        collection do
          get :api_key_request
        end
      end
    end
  end

  get 'suggester/query'
  get 'suggester/place'
  get 'suggester/place_from_poland', :as => :place_from_poland

  resources :tags, :only => [:create]
  resources :administrative_divisions, :only => [:index]

  get 'geocoder/search'

  match "/hello"                      => 'pages#hello', :id => 'hello', :as => :hello
  match "accept_terms"               => 'static_pages#accept_terms_of_service'

  I18n.available_locales.each do |locale|
    match "#{I18n.t('routes.pages', :locale => locale)}/:id" => 'pages#show', :as => :"#{locale.to_s.underscore}_page"
  end

  root :to => 'pages#show', :id => 'home'
end

app/controllers/relicbuilders_controller.rb
# -*- encoding : utf-8 -*-
class RelicbuildersController < ApplicationController
  before_filter :enable_floating_fancybox

  before_filter :authenticate_user!, :except => [:geodistance, :administrative_level]
  before_filter :enable_fancybox, :only => [:geodistance]
  before_filter :redirect_finished_relic, :only => [:address, :details, :photos, :update]
  helper_method :address_params

  def new
    @relic = Relic.new :kind => 'SA', :existence => 'social'
    @location = LocationBuilder.new params[:location]
    if @location.foreign_relic?
      if geo = @location.geocode_result
        @relic.latitude   = geo.latitude
        @relic.longitude  = geo.longitude
      end
    elsif @location.polish_place?
      pq = PreparedQuery.new @location.polish_place
      @places = if pq.exists?
        Place.where(["LOWER(name) LIKE ?", "#{pq.clean.downcase}"]).map do |p|
          p.conditional_geocode!
          p
        end
      else
        []
      end
      @relic.place = @places.first if @places.size == 1
    end
    @relic.kind = 'ZE' if @location.relic_group?
    @relic.parent_id = params[:parent_id]
  end

  def geodistance
    @relics = Search.new(:per_page => 20,
      :lat => params.get_deep('relic', 'latitude'),
      :lon => params.get_deep('relic', 'longitude'),
      :load => true
    ).perform
    if @relics.total.zero?
      flash[:notice] = t('notices.there_is_no_relics_in_the_area')
      render :js => "window.location = '#{address_relicbuilder_path(address_params)}';"
    end
  end

  def administrative_level
    @voivodeship = Voivodeship.find_by_id params.get_deep('relic', 'voivodeship_id')
    @district    = District.find_by_id params.get_deep('relic', 'district_id')
    @commune     = Commune.find_by_id params.get_deep('relic', 'commune_id').to_s.split(',')

    @district    = @commune.district     if @commune
    @voivodeship = @district.voivodeship if @district

    render :partial => 'administrative_level', :layout => false, :locals => {:relic => nil}
  end

  def address
    geo_hash = Place.find_by_position(params[:latitude], params[:longitude])
    place = if geo_hash && geo_hash.get_deep(:objs, :place)
      geo_hash.get_deep(:objs, :place)
    elsif params[:place_id].present?
      Place.find(params[:place_id])
    end
    if @relic = Relic.find_by_id(params[:id])
      @relic.build_state = 'address_step'
    else
      @relic = if geo_hash && geo_hash[:foreign]
        ForeignRelic.new(
          :build_state  => 'address_step',
          :country_code => geo_hash[:country_code],
          :fprovince    => geo_hash[:voivodeship],
          :fplace       => geo_hash[:place]
        )
      else
        Relic.new :build_state => 'address_step'
      end
      @relic.place      = place if place
      @relic.parent_id  = params[:parent_id]
      @relic.kind       = params[:kind]
      @relic.existence  = params[:existence]
      @relic.street     = (geo_hash || {}).get_deep(:street) || @relic.street
      @relic.latitude   = (geo_hash || params).get_deep(:latitude)
      @relic.longitude  = (geo_hash || params).get_deep(:longitude)
    end
  end

  def create
    attributes = (params[:relic] || {}).except(:voivodeship_id, :district_id, :commune_id)
    @relic = Relic.new attributes
    @relic = ForeignRelic.new(attributes) if @relic.foreign_relic?
    @relic.user_id = current_user.id
    if @relic.save
      redirect_to details_relicbuilder_path(:id => @relic)
    else
      render :address
    end
  end

  def details
    @relic = Relic.find(params[:id])
    @relic.build_state = 'details_step'
  end

  def photos
    @relic = Relic.find(params[:id])
    @relic.build_state = 'photos_step'
  end

  def update
    @relic = Relic.find(params[:id])
    @relic.attributes = (params[:relic] || {}).except(:voivodeship_id, :district_id, :commune_id)
    if @relic.build_state == 'photos_step' && @relic.license_agreement != "1"
      @relic.photos.where(:user_id => current_user.id).destroy_all
      flash[:notice] = t('notices.unpublished_photos_has_been_delete')
      redirect_to photos_relicbuilder_path(:id => @relic) and return
    end
    if @relic.save
      case @relic.build_state
      when 'address_step'
        redirect_to details_relicbuilder_path(:id => @relic)
      when 'details_step'
        redirect_to photos_relicbuilder_path(:id => @relic)
      when 'photos_step'
        if @relic.update_attributes :build_state => "finish_step"
          redirect_to @relic, :notice => (@relic.is_group? ? t('notices.new_group_relic_has_been_added') : t('notices.new_relic_has_been_added'))
        else
          render @relic.invalid_step_view
        end
      when 'finish_step'
        redirect_to @relic
      else
        raise Exception.new("Incorrect build step: #{@relic.build_state}")
      end
    else
      render @relic.invalid_step_view
    end
  end

  protected
    def address_params
      (params[:relic] || params).slice(:latitude, :longitude, :place_id, :parent_id, :kind, :existence)
    end

    def redirect_finished_relic
      @relic = Relic.find_by_id(params[:id])
      if @relic and @relic.build_state == 'finish_step'
        redirect_to @relic
      end
    end

end

app/views/relicbuilders/_administrative_level.html.haml
:ruby
  @voivodeship ||= relic.try(:voivodeship)
  @district    ||= relic.try(:district) || @voivodeship.try(:districts).try(:first)
  @commune     ||= relic.try(:commune) || @district.try(:communes).try(:first)

.administrative-level
  .one-third
    = label_tag 'relic[voivodeship_id]', t('views.relicbuilders.administrative_level.voivodeship')
    = select 'relic', 'voivodeship_id',  voivodeship_collection, selected: @voivodeship.try(:id).to_s
  - if @voivodeship
    .one-third
      = label_tag 'relic[district_id]', t('views.relicbuilders.administrative_level.district')
      = select 'relic', 'district_id', district_collection, selected: @district.try(:id).to_s
  - if @district
    .one-third
      = label_tag 'relic[commune_id]', t('views.relicbuilders.administrative_level.commune')
      = select 'relic', 'commune_id', commune_collection, selected: @commune.try(:virtual_id).to_s
  - if @commune
    .row
      = label_tag 'relic[place_id]', t('views.relicbuilders.administrative_level.city')
      = select 'relic', 'place_id',  place_collection, selected: relic.try(:place_id).to_s
  - if relic && relic.errors[:place] && relic.place_id.blank?
    .error
      = t('views.relicbuilders.administrative_level.error')

app/views/relicbuilders/_parent_relic.html.haml
- if parent_relic
  %h2.complex
    = t('views.relicbuilders.parent_relic.complex')
    %br
    = parent_relic.identification

app/views/relicbuilders/_step2.html.haml
%section.creator-step
  / = render :partial => 'parent_relic', :object => @relic.parent
  %p.intro= t('views.relicbuilders.address.intro1')
%form(class="formtastic")
  %div(ng-show="relic.foreign_relic")
    .select
      %label= t('views.relicbuilders.new.country_code')
      = country_code_select(:relics, :country_code, nil, {}, {'ng-model' => 'location.country_code'})

    %label= t('activerecord.attributes.relic.fprovince')
    %input(type="text" ng-model="location.fprovince")

    %label= t('activerecord.attributes.relic.fplace')
    %input(type="text" ng-model="location.fplace")

  %div(ng-hide="relic.foreign_relic")
    .administrative-level
      .one-third
        %label(for="relic_voivodeship_id")
          = t('views.relicbuilders.administrative_level.voivodeship')
        %select(id="relic_voivodeship_id" ng-model="administrative.selected.voivodeship"
          ng-change="getAdministrative('voivodeship')" ng-options="o.name for o in administrative.options.voivodeships")
      .one-third(ng-show="administrative.selected.voivodeship")
        %label(for="relic_district_id")
          = t('views.relicbuilders.administrative_level.district')
        %select(id="relic_district_id" ng-model="administrative.selected.district"
          ng-change="getAdministrative('district')" ng-options="o.name for o in administrative.options.districts")
      .one-third(ng-show="administrative.selected.district")
        %label(for="relic_commune_id")
          = t('views.relicbuilders.administrative_level.commune')
        %select(id="relic_commune_id" ng-model="administrative.selected.commune"
          ng-change="getAdministrative('commune')" ng-options="o.name for o in administrative.options.communes")
      .row(ng-show="administrative.selected.commune")
        %label(for="relic_place_id")
          = t('views.relicbuilders.administrative_level.city')
        %select(id="relic_place_id" ng-model="administrative.selected.place"
          ng-change="getAdministrative('place')" ng-options="o.name for o in administrative.options.places")
    .clearfix
  .street_input(ng-show="knownAddress()")
    #relic_street_input(class="string clearfix optional stringish")
      %label(for="relic_street")= t('activerecord.attributes.relic.street')
      .input
        %span.block= t('formtastic.hints.relic.street')
        %input(id="relic_street" type="text" ng-model="location.street")

  %a(class="toggle_street_input" href prevent-default ng-click="toggleKnownAddress()")
    %span(ng-show="!knownAddress()")
      = t('views.relics.edit.location.known_address')
    %span(ng-show="knownAddress()")
      = t('views.relics.edit.location.unknown_address')

  .actions.relic-address
    %a(class="back" ng-click="goToStep(1)" prevent-default)
      = t('views.relicbuilders.stages.back').html_safe
    %button(ng-click="goToStep(3)" prevent-default)
      =t('views.relicbuilders.next_step_html')

app/views/relicbuilders/_step3.html.haml
%section.creator-step
  / = render :partial => 'parent_relic', :object => @relic.parent
  %p.intro= t('views.relicbuilders.details.intro1')
%form(class="formtastic")
  #relic_identification_input(class="string clearfix stringish")
    %label(for="relic_identification")
      = t('views.relicbuilders.details.name')
    .input
      %input(id="relic_identification" type="text" ng-model="relic.identification")
  #relic_reason_input(class="text clearfix")
    %label(for="relic_reason")
      = t('views.relicbuilders.details.reason')
    .input
      %textarea(id="relic_reason" ng-model="relic.reason" redactor="{focus: false, buttons: ['bold', 'italic', 'link', 'unorderedlist'], lang: 'pl'}" rows="20")

  .actions.relic-details
    %a(class="back" ng-click="goToStep(2)" prevent-default)
      = t('views.relicbuilders.stages.back').html_safe
    %button(ng-click="goToStep(4)")
      = t('views.relicbuilders.next_step_html')

app/views/relicbuilders/_step4.html.haml
%section.creator-step
  / = render :partial => 'parent_relic', :object => @relic.parent
  %p.intro= t('views.relicbuilders.photos.intro1')
%section.edit.photos
  TODO Add photos in Angular
  / TODO
  / = semantic_form_for @relic, :url => relicbuilder_path(:id => @relic), :html => { :multipart => true }, :method => :put  do |f|
  /   = f.hidden_field :build_state
  /   = f.input :description, :input_html => { :class => 'redactor' }
  /   %h4= t('views.relicbuilders.photos.label')
  /   %p.intro= t('views.relicbuilders.photos.intro2')
  /   .photo-attributes{:'data-replace' => ".photo-attributes"}
  /     - @relic.photos.each do |photo|
  /       - if photo.user_id == current_user.id
  /         = f.semantic_fields_for :photos, photo do |f2|
  /           .photo
  /             .column-left
  /               .preview
  /                 = image_tag photo.file.midi.url
  /               - if photo.user_id == current_user.id
  /                 = link_to t('views.relics.edit.photos.delete_photo'), relic_photo_path(@relic.id, photo.id, :build => true),
  /                   :method => :delete,
  /                   :remote => true,
  /                   :confirm => t('views.relics.edit.photos.delete_confirm', :editable => false),
  /                   :class => "remove_photo"

  /             .column-right
  /               = f2.input :author, :input_html => { :class => "author" }
  /               = f2.input :date_taken, :input_html => { :class => "date_taken" }
  /       - else
  /         .photo
  /           .column-left
  /             .preview
  /               = image_tag photo.file.midi.url
  /           .column-right
  /             %label= t('activerecord.attributes.photo.author')
  /             %p= photo.author
  /             %label= t('activerecord.attributes.photo.date_taken')
  /             %p= photo.date_taken

  /     .photo.hidden
  /       .column-left
  /         .preview.preview-placeholder

  /       .column-right
  /         %p
  /           %strong= t('views.relics.edit.photos.loading')
  /           = link_to 'anuluj', '#', :class => "cancel_upload"
  /         %p
  /           .progressbar
  /             .value 0%

  /     .photo-upload
  /       = file_field_tag "photo[file]", :class => 'photo_upload' + (@relic.photos.length > 0 ? "" : " first"), :"data-url" => "#{relic_photos_path(@relic, :build => true)}"

  /     = f.input :license_agreement, :input_html => { :checked => 'checked' }, :as => :boolean, :label => t('views.relics.edit.photos.statement_html')

  /   .actions.relic-photos
  /     = link_to t('views.relicbuilders.stages.back').html_safe, details_relicbuilder_path(:id => @relic.try(:id)), :class => "back"
  /     %button= (@relic.is_group? ? t('views.relicbuilders.photos.submit_relic_group') : t('views.relicbuilders.photos.submit'))

app/views/relicbuilders/new.html.haml
- location = LocationBuilder.new(params[:location])
- if location.relic_group?
  :css
    span.r_ze { display: inline; }
    span.r_sa { display: none; }

#fancybox
.edit_relic.new_relic
  = render :partial => "relicbuilders/stages", :locals => { :stage => 1 }
  .creator
    %section.main
      %section.creator-step
        = render :partial => 'parent_relic', :object => @relic.parent
        %aside
        %h3.intro= t('views.relicbuilders.new.intro1_html')
      %section.creator-step
        = semantic_form_for location, :as => 'location', :url => new_relicbuilder_path(params), :method => :get, :remote => true do |f|
          - unless @relic.parent
            = f.input :relic_group, :as => :boolean, :label => t('views.relicbuilders.new.add_relic_group')
            %p.info-tooltip= link_to((image_tag 'icon-info.png', alt: 'info'), '#', :id => "relic_group_popover", :class => "js-popover relic-group", :"data-content-id" => "group_body", :"data-title-id" => "group_title")
          %script(type="text/html" id="group_title")
            %p= t('views.relicbuilders.new.info_header_relic_group')
            %p.close= link_to "zamknij", "#", :class => "close_popover", :"data-popover-id" => "relic_group_popover"
          %script(type="text/html" id="group_body")
            %span.relic-text
              = t('views.relicbuilders.new.info_relic_group')
          = f.input :foreign_relic, :as => :boolean, :label => t('views.relicbuilders.new.add_foreign_relic')
          = f.input :existence, :as => :boolean, :label => t('views.relicbuilders.new.non_existed')
          %p.info-tooltip= link_to((image_tag 'icon-info.png', alt: 'info'), '#', :id => "nonexisted_relic_popover", :class => "js-popover non-existed", :"data-content-id" => "nonexisted_body", :"data-title-id" => "nonexisted_title")
          %script(type="text/html" id="nonexisted_title")
            %p= t('views.relicbuilders.new.info_header_nonexisted_relic')
            %p.close= link_to "zamknij", "#", :class => "close_popover", :"data-popover-id" => "nonexisted_relic_popover"
          %script(type="text/html" id="nonexisted_body")
            %span.relic-text
              = t('views.relicbuilders.new.info_nonexisted_relic')
          .clear
          .field.text.search.marker-box
            .polish-location.polish-location-input-container{:style => "#{ 'display: none;' unless f.object.foreign_relic.to_i.zero?}"}
              = f.input :polish_place, :label => t('views.relicbuilders.new.place')
            .foreign-location{:style => "#{ 'display: none;' if f.object.foreign_relic.to_i.zero?}"}
              .select
                = f.label :country_code, t('views.relicbuilders.new.country_code')
                = f.country_code_select :country_code
              = f.input :original_name, :label => t('views.relicbuilders.new.original_name')
              = f.input :polish_name, :label => t('views.relicbuilders.new.polish_name')
          .actions
            %button{:class => 'btn'}
              = t('views.relicbuilders.new.search_html')
      .polish-location{:style => "#{ 'display: none;' unless location.foreign_relic.to_i.zero?}"}
        - if defined? @places
          - if @places.blank?
            = t('views.relicbuilders.new.no_results')
          - elsif @places.size > 1
            %section.creator-step
              %h3= t('views.relicbuilders.new.select_place')
              .places-wrapper
                %ul.places
                  - @places.each do |place|
                    %li
                      = (place.location_names.first(place.location_names.size - 1) << "<strong>#{place.name}</strong>").join(' > ').html_safe
                      = link_to t('views.relicbuilders.new.choose_html'), 'javascript: void(0);', 'data-place_id' => place.id, 'data-coordinates' => "#{place.latitude}, #{place.longitude}"

      %section.creator-step.location
        = semantic_form_for @relic, :url => geodistance_relicbuilder_path, :method => :get, :remote => true do |f|
          %h3.select-on-map= t('views.relicbuilders.new.select_on_map')
          .column
            #map_canvas{ :style => "width: 515px; height: 380px;" }
          .column
            .marker-helper
              %h3= t('views.relicbuilders.new.drag_marker')
              .marker-holder
                = image_tag 'marker.png', :id => 'marker', alt: 'marker'
            .actions{:style => 'display:none;'}
              %button= t('views.relicbuilders.next_step_html')
          = f.hidden_field :existence
          = f.hidden_field :kind
          = f.hidden_field :parent_id
          = f.hidden_field :place_id
          = f.hidden_field :latitude
          = f.hidden_field :longitude

app/views/relicbuilders/new_old.html.haml
- location = LocationBuilder.new(params[:location])
- if location.relic_group?
  :css
    span.r_ze { display: inline; }
    span.r_sa { display: none; }

#fancybox
.edit_relic.new_relic
  = render :partial => "relicbuilders/stages", :locals => { :stage => 1 }
  .creator
    %section.main
      %section.creator-step
        = render :partial => 'parent_relic', :object => @relic.parent
        %aside
        %h3.intro= t('views.relicbuilders.new.intro1_html')
      %section.creator-step
        = semantic_form_for location, :as => 'location', :url => new_relicbuilder_path(params), :method => :get, :remote => true do |f|
          - unless @relic.parent
            = f.input :relic_group, :as => :boolean, :label => t('views.relicbuilders.new.add_relic_group')
            %p.info-tooltip= link_to((image_tag 'icon-info.png'), '#', :id => "relic_group_popover", :class => "js-popover relic-group", :"data-content-id" => "group_body", :"data-title-id" => "group_title")
          %script(type="text/html" id="group_title")
            %p= t('views.relicbuilders.new.info_header_relic_group')
            %p.close= link_to "zamknij", "#", :class => "close_popover", :"data-popover-id" => "relic_group_popover"
          %script(type="text/html" id="group_body")
            %span.relic-text
              = t('views.relicbuilders.new.info_relic_group')
          = f.input :foreign_relic, :as => :boolean, :label => t('views.relicbuilders.new.add_foreign_relic')
          = f.input :existence, :as => :boolean, :label => t('views.relicbuilders.new.non_existed')
          %p.info-tooltip= link_to((image_tag 'icon-info.png'), '#', :id => "nonexisted_relic_popover", :class => "js-popover non-existed", :"data-content-id" => "nonexisted_body", :"data-title-id" => "nonexisted_title")
          %script(type="text/html" id="nonexisted_title")
            %p= t('views.relicbuilders.new.info_header_nonexisted_relic')
            %p.close= link_to "zamknij", "#", :class => "close_popover", :"data-popover-id" => "nonexisted_relic_popover"
          %script(type="text/html" id="nonexisted_body")
            %span.relic-text
              = t('views.relicbuilders.new.info_nonexisted_relic')
          .clear
          .field.text.search.marker
            .polish-location{:style => "#{ 'display: none;' unless f.object.foreign_relic.to_i.zero?}"}
              = f.input :polish_place, :label => t('views.relicbuilders.new.place')
            .foreign-location{:style => "#{ 'display: none;' if f.object.foreign_relic.to_i.zero?}"}
              .select
                = f.label :country_code, t('views.relicbuilders.new.country_code')
                = f.country_code_select :country_code
              = f.input :original_name, :label => t('views.relicbuilders.new.original_name')
              = f.input :polish_name, :label => t('views.relicbuilders.new.polish_name')
          .actions
            %button{:class => 'btn'}
              = t('views.relicbuilders.new.search_html')
      .polish-location{:style => "#{ 'display: none;' unless location.foreign_relic.to_i.zero?}"}
        - if defined? @places
          - if @places.blank?
            = t('views.relicbuilders.new.no_results')
          - elsif @places.size > 1
            %section.creator-step
              %h3= t('views.relicbuilders.new.select_place')
              .places-wrapper
                %ul.places
                  - @places.each do |place|
                    %li
                      = (place.location_names.first(place.location_names.size - 1) << "<strong>#{place.name}</strong>").join(' > ').html_safe
                      = link_to t('views.relicbuilders.new.choose_html'), 'javascript: void(0);', 'data-place_id' => place.id, 'data-coordinates' => "#{place.latitude}, #{place.longitude}"

      %section.creator-step.location
        = semantic_form_for @relic, :url => geodistance_relicbuilder_path, :method => :get, :remote => true do |f|
          %h3.select-on-map= t('views.relicbuilders.new.select_on_map')
          .column
            #map_canvas{ :style => "width: 515px; height: 380px;" }
          .column
            .marker-helper
              %h3= t('views.relicbuilders.new.drag_marker')
              .marker-holder
                = image_tag 'marker.png', :id => 'marker'
            .actions{:style => 'display:none;'}
              %button= t('views.relicbuilders.next_step_html')
          = f.hidden_field :existence
          = f.hidden_field :kind
          = f.hidden_field :parent_id
          = f.hidden_field :place_id
          = f.hidden_field :latitude
          = f.hidden_field :longitude

app/views/relicbuilders/photos.html.haml
.edit_relic.new_relic
  = render :partial => "stages", :locals => { :stage => 4 }
  .creator
    %section.main
      %section.creator-step
        = render :partial => 'parent_relic', :object => @relic.parent
        %p.intro= t('views.relicbuilders.photos.intro1')
      %section.edit.photos
        = semantic_form_for @relic, :url => relicbuilder_path(:id => @relic), :html => { :multipart => true }, :method => :put  do |f|
          = f.hidden_field :build_state
          = f.input :description, :input_html => { :class => 'redactor' }
          %h4= t('views.relicbuilders.photos.label')
          %p.intro= t('views.relicbuilders.photos.intro2')
          .photo-attributes{:'data-replace' => ".photo-attributes"}
            - @relic.photos.each do |photo|
              - if photo.user_id == current_user.id
                = f.semantic_fields_for :photos, photo do |f2|
                  .photo
                    .column-left
                      .preview
                        = image_tag photo.file.midi.url, alt: photo.alternate_text
                      - if photo.user_id == current_user.id
                        = link_to t('views.relics.edit.photos.delete_photo'), relic_photo_path(@relic.id, photo.id, :build => true),
                          :method => :delete,
                          :remote => true,
                          :confirm => t('views.relics.edit.photos.delete_confirm', :editable => false),
                          :class => "remove_photo"

                    .column-right
                      = f2.input :author, :input_html => { :class => "author" }
                      = f2.input :date_taken, :input_html => { :class => "date_taken" }
              - else
                .photo
                  .column-left
                    .preview
                      = image_tag photo.file.midi.url, alt: photo.alternate_text
                  .column-right
                    %label= t('activerecord.attributes.photo.author')
                    %p= photo.author
                    %label= t('activerecord.attributes.photo.date_taken')
                    %p= photo.date_taken

            .photo.hidden
              .column-left
                .preview.preview-placeholder

              .column-right
                %p
                  %strong= t('views.relics.edit.photos.loading')
                  = link_to 'anuluj', '#', :class => "cancel_upload"
                %p
                  .progressbar
                    .value 0%

            .photo-upload
              = file_field_tag "photo[file]", :class => 'js-piwik-added-a-new-photo photo_upload' + (@relic.photos.length > 0 ? "" : " first"), :"data-url" => "#{relic_photos_path(@relic, :build => true)}"

            = f.input :license_agreement, :input_html => { :checked => 'checked' }, :as => :boolean, :label => t('views.relics.edit.photos.statement_html')

          .actions.relic-photos
            = link_to t('views.relicbuilders.stages.back').html_safe, details_relicbuilder_path(:id => @relic.try(:id)), :class => "back"
            %button.js-piwik-added-a-new-monument= (@relic.is_group? ? t('views.relicbuilders.photos.submit_relic_group') : t('views.relicbuilders.photos.submit'))